apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argus-api
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: argus
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argus-worker
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: argus
      app.kubernetes.io/component: worker

