apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argus-local
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/gaurav-gs7/argus-api
    newTag: dev
  - name: ghcr.io/gaurav-gs7/argus-worker
    newTag: dev
  - name: ghcr.io/gaurav-gs7/argus-ai
    newTag: dev
patches:
  - path: configmap-patch.yaml

