apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argus-api
spec:
  minAvailable: 1
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argus-worker
spec:
  minAvailable: 1

